import testImage from './assets/imgs/individual/alex.jpg'

const ProfileBack = ({className, id, profile}) => {
    const testString = "It is 5:15 AM as I write this and I genuinely believe my soul has the mandate of heaven. I'm like if the Jimmy Timmy Power Hour was a person. I'm like if you averaged every white guy in your local mall between the ages of 16 and 24. I'm like Warren Buffet with Benjamin Button disease. I'm like if the infinite monkeys were trying to write High School Musical 2 instead. I'm Carlton Banks minus the money, plus a gambling addiction.\n\nOk time for a real bio. Hi, my name is Eddie!!! You can tell it's me because of the way I am. In lieu of actual facts about me, here are some banger tweets I've made over the years:\n\n\"one must imagine the itsy bitsy spider happy\"\n\"Dating is so easy all you have to do is send her any photo and then say 'us'\"\n\"The 5 W's of owl journalism: who who who who who\"\n\"Gotta be crazy to be like oh hey that guy from my cancer support group i wonder how hes doing JOHN KRAMER DID WHAT NOW\"\n\"Group project partner just called me edwin how do i kill him\"\n\"NOTEWORTHY? Ermmm, this is epic! Come on boys, lets do a song! *Pulls out pitch pipe*\"\n\"the irony of arranging im just ken while my girlfriend sleeps soundly in my own bed is not lost on me\"\n\"Gf keeps saying i have a slutty little waist\"\n\"(Guy whose been in a coma for 40 years): Wow this is EXACTLY like 1984\"\n\"When they say something so agoraphobic that you gotta hit them with that extrovert stare\"\n\"Testing my physiognomy skills by seeing who gets off of the tirana-barcelona plane and immediately deciding their ethnicity\"\n\"She Beastie on my Boys till im Intergalactic\"\n\"Ok at this point the mission is quite possible\"\n\"What if you were making out n they say... ALL HAIL PLANKTON... thatd be so f***ed up 😥\"\n\"...i would like to remind everyone about the time i was matched against someone in a hazbin hotel shirt during a magic the gathering tournament and after i beat him he proceeded to drink straight from a 2 liter bottle of pepsi\"\n\"insanely proud of my sister for getting into med school but now i have an issue because she is becoming the ideal immigrant child so i think i have to Highlander her\"\n\"they feed us poison (college parties) so we buy their \"cures\" (red solo cup beer) while they suppress our medicine (nyquil from the cap)\"\n\"Calling each of my asian friends with a dynastic last name a nepo baby\"\n\"Me when im thinking: Wow this is just like Disco Elysium\"\n\"God the costco pumpkin pie is so efficient it makes me weep tears of euphoria\"\n\"Dodging the discord furry allegations\"\n\"Ok wise guy lets see YOU take a crack addict\"\n\n\n\nQuil Squared recipe:\n\nOne part DayQuil\nOne part NyQuil\nOne part Olive Oil\nOne part Everclear\n\n\nI'm like slam poetry but not bad. I'm like Abraham Lincoln if he never became president. I'm Joe Rogan with hair. I am NOT okay. I'm going to sleep.\n\n\n\n\n\n\n\n\nI'm Phineas AND Ferb."

    return (
        <div className={`${className}`} id={`${id}`}>
            <div className="profile-information back-information text-left">
                <p>{testString}</p>
            </div>
        </div>
    );
};

export default ProfileBack;